### ISSUE TITLE
JSDoc not hidden

### ISSUE THREAD

**Issue by joezimjs** [estruyf/vscode-hide-comments#11]
When I hide comments, the JSDoc comments are still visible. These should also be hidden.

Show comments:
![image](https://user-images.githubusercontent.com/1313898/134983998-9a32fcef-6b98-4374-a527-bcfad53e60cc.png)

Hide Comments:
![image](https://user-images.githubusercontent.com/1313898/134984050-c5d5f04d-be77-44d8-990a-a409b436697b.png)

**Comment by estruyf** [comment]
Thanks @joezimjs, I fix this + the blocks will now automatically get folded on hiding the comments.

**Comment by joezimjs** [comment]
Awesome! Thanks for the quick turnaround! Looks good!
