### ISSUE TITLE
Publish the extension to Open VSX Registry

### ISSUE THREAD

**Issue by hizani** [estruyf/vscode-hide-comments#18]
Hi, I'm a Code OSS user, an open source version of VS Code. It's the same code but without Microsoft's telemetry, branding and licensing.

I would like to request, if possible, to add your extension to the [open-vsx.org](https://open-vsx.org) market as it is probably illegal to use the official Microsoft extension marketplace on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional information on how to publish an extension to Open VSX Registry can be obtained [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by estruyf** [comment]
Thanks for the suggestion! I might have to try Code OSS as well. Any guides on this?

BTW: The latest version has just been released on Open VSX - https://open-vsx.org/extension/eliostruyf/vscode-hide-comments - in the future, each new release will automatically be published there as well.

**Comment by hizani** [comment]
@estruyf Thanks for publishing! 

To get Code OSS you need to build it from [source](https://github.com/microsoft/vscode) or find a pre-build version. There is also a pre-build FOSS fork of VSCode called [VSCodium](https://vscodium.com/) which I think is preferable if your package manager doesn't provide Code OSS build or if you don't use one. 

You can find VSCode -> VSCodium migration guide and more on their [github](https://github.com/VSCodium/vscodium/blob/master/DOCS.md).

**Comment by estruyf** [comment]
Thanks @hizani, installed VSCodium earlier with homebrew. Also published other extensions to the Open VSX marketplace.

![Xnapper-2022-08-12-14 20 44](https://user-images.githubusercontent.com/2900833/184352764-0ab83456-d14b-4c7d-b757-73b8bef0e2c6.png)
