### ISSUE TITLE
Disable annoying 'Do you want to hide comments in this project' popup

### ISSUE THREAD

**Issue by ALIENQuake** [estruyf/vscode-hide-comments#2]
Hi,

every time I launch VSCode I get annoying 'Do you want to hide comments in this project' popup. When I want to 'hide comments' I use appropriate command. Hiding comments may or may not be a common task for a project. When it is not common, this popup is annoying. How to disable it?

**Comment by estruyf** [comment]
Should only be asked the first time. When you click on `yes` or `no` it will store it and should not ask it the next time.

**Comment by ALIENQuake** [comment]
@estruyf It popups every time when I open any file using "Open in VSCode" right-click menu. I should be able to disable this popup globally and never see it again.

**Comment by ALIENQuake** [comment]
@estruyf Hey, any update on this?

**Comment by estruyf** [comment]
Sorry @ALIENQuake, I had a bike accident last week and broke my back. You can globally disable this when you set this in your user settings. Go to `open user settings`, search for `eliostruyf`, and click on `Edit in settings.json`.

VSCode will automatically add a global setting line with `"eliostruyf.hideCommentsActive": false`. This way it will always be disabled by default.

**Comment by ALIENQuake** [comment]
@estruyf I'm sorry, thanks for the workaround.

**Comment by geekrelief** [comment]
> Sorry @ALIENQuake, I had a bike accident last week and broke my back. You can globally disable this when you set this in your user settings. Go to `open user settings`, search for `eliostruyf`, and click on `Edit in settings.json`.
> 
> VSCode will automatically add a global setting line with `"eliostruyf.hideCommentsActive": false`. This way it will always be disabled by default.

I just installed the extension, but adding "eliostruyf.hideCommentsActive" in my settings.json doesn't work for me.  Is there another option? I'd prefer the extension to not hide by default, since I have shortcut keys to toggle the comments.
