### ISSUE TITLE
Add a keyboard shortcut

### ISSUE THREAD

**Issue by Aarbel** [estruyf/vscode-hide-comments#20]
@estruyf thanks a lot for this plugin. A lot of people where waiting it for it: https://github.com/microsoft/vscode/issues/46505

Would it be possible to implement a keyboard shortcut to toggle comments fold / fold ?

Thanks a lot

**Comment by estruyf** [comment]
Hi @Aarbel, yes you can do this in Visual Studio Code as follows:

- Open the command palette
- Use the `Preferences: Open Keyboard Shortcuts` command
- Search for: `@command:hidecomments.hide` and `@command:hidecomments.show`
- Double click on the command, and you are able to define your keyboard binding

**Comment by 0xPhaze** [comment]
A toggle command `@command:hidecomments.toggle`would be greatly appreciated to be able to bind it to one key!

**Comment by offlinemark** [comment]
^ Agreed! A toggle would be great.

**Comment by estruyf** [comment]
Thanks again @Aarbel and @offlinemark, for the suggestion. I have added the `Hide Comments: Toggle the show/hide of all comments` command, you can use this command to add it with the keyboard shortcut of your choice. 

> More information can be found on the extension its readme.
