### ISSUE TITLE
Add Toggle the show/hide of all comments + lines by regex

### ISSUE THREAD

**Issue by nisedo** [estruyf/vscode-hide-comments#25]
Hi, could you add the Keyboard Shortcuts option to Toggle both the show/hide of all comments and the lines by regex in one button please?

Currently there is only the "Toggle the show/hide of all comments" Keyboard Shortcuts option.

Thanks!

**Comment by estruyf** [comment]
Hi @nisedo, just to clarify, do you want the `Toggle the show/hide of all comments` to toggle both the comments and regex?

**Comment by nisedo** [comment]
Hi @estruyf, yes exactly! One toggle shortcut for both 👌

**Comment by estruyf** [comment]
Releasing version 1.9.0 with this change included.
