### ISSUE TITLE
Option to turn off folding

### ISSUE THREAD

**Issue by antislukas** [estruyf/vscode-hide-comments#28]
Hi and thanks for this great extension. 
This is more of a feature request: could there be a setting to turn of folding of multi-line comments? I've read that this behavior was asked for but it would be great if this could be toggled.
Why am I asking? I'm using this extension a bit differently and toggle the color of the comments so that they don't distract me but are still slightly visible.
PS: I'd be also happy if someone could tell me what I need to add to the settings file in order to stop the folding.

**Comment by estruyf** [comment]
Thanks @antislukas for the suggestion. I just released version `1.10.0` with this functionality included. You can configure the behavior with the new `hideComments.foldOnHide` setting, which is set to `true` by default.

**Comment by antislukas** [comment]
Awesome. Thanks @estruyf !
