### ISSUE TITLE
Need to add keyboard shortcut to enable/disable, or a button in the toolbar to toggle between hiding/showing comments.

### ISSUE THREAD

**Issue by cfoxy17** [estruyf/vscode-hide-comments#3]
Sometimes I want to see comments like when I'm debugging, other times I don't want to see them like when I just want to look at the code to see what it's doing. If a keyboard shortcut (preferably) or a button in the toolbar was there to let you toggle comments on and off, that would be OP.

**Comment by estruyf** [comment]
@cfoxy17 you can define any keyboard shortcut to any of the available commands in VSCode. In order to do this, do the following:

- Run `Preferences: Open keyboard shortcuts`
- Search for `Hide Comments`
- Map the keyboard shortcut you want to use
