### ISSUE TITLE
When I uninstall this extension the comments are still hidden.

### ISSUE THREAD

**Issue by cfoxy17** [estruyf/vscode-hide-comments#4]
I have no idea how to fix this. already restarted vscode.

**Comment by estruyf** [comment]
This is because there is no `uninstall` trigger on VSCode. Make sure to remove the settings from your `.vscode/settings.json` file.

**Comment by estruyf** [comment]
Unfortunately, VSCode does not provide an uninstall hook/event. There is a way to add a script, but this doesn't seem to run in the context of your project/VSCode workspace. I have added a new section on the README to explain the steps to take when resetting it to the original state: https://github.com/estruyf/vscode-hide-comments#removing-the-extension
