### ISSUE TITLE
Instead of hiding comments by making them transparent it should collapse them so there isn't empty whitespace.

### ISSUE THREAD

**Issue by cfoxy17** [estruyf/vscode-hide-comments#6]
Instead of making the comments transparent, the comments should be collapsed like you can do by clicking on the bar on the left near the page #'s. 

This way we don't have a bunch of empty white lines.

**Comment by joezimjs** [comment]
Personally, I think this would be cool and would remove my need for a fix to #11, but I don't know how you'd collapse single-line comments.

**Comment by estruyf** [comment]
Folding/unfolding for block comments is added in version `1.4.0`.
